system:
    default:
        image_variations:
            ez_progressive_placeholder:
                reference: ~
                filters:
                    - { name: geometry/scale, params: [24, 24] }
                post_processors:
                    jpegoptim: { strip_all: true, max: 60 }
            ez_progressive_admin:
                reference: ~
                filters:
                    - { name: geometry/scaledownonly, params: [900, 900] }
        field_templates:
            -
                template: '@ezdesign/ezprogressiveimage/fields/ez_image_field.html.twig'
                priority: 100
