system:
    default:
        image_variations:
            ez_progressive_placeholder:
                reference: null
                filters:
                    -
                        name: geometry/scale
                        params: [24, 24]
        field_templates:
            -
                template: '@EzProgressiveImage/fields/ez_image_field.html.twig'
                priority: 100