parameters:
    ez.progressive.image.twig.extension.class: Gie\EzProgressiveImageBundle\Twig\ImageExtension
    ez.progressive.image.placeholder.variation.name: 'ez_progressive_placeholder'

services:
    ez.progressive.image.twig.extension:
        class: '%ez.progressive.image.twig.extension.class%'
        parent: ezpublish.twig.extension.image
        calls:
            - method: setConfig
              arguments:
                - '@ezpublish.image_alias.variation_path_generator'
                - '@ezpublish.fieldType.ezimage.io_service'
                - '%ez.progressive.image.placeholder.variation.name%'
        tags:
             - { name: twig.extension }
